# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import forecast_pb2 as forecast__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in forecast_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForecastServiceStub(object):
    """─── Main Service ────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitForecastJob = channel.unary_unary(
                '/meridian.ForecastService/SubmitForecastJob',
                request_serializer=forecast__pb2.ForecastRequest.SerializeToString,
                response_deserializer=forecast__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/meridian.ForecastService/GetJobStatus',
                request_serializer=forecast__pb2.JobID.SerializeToString,
                response_deserializer=forecast__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.GetForecastResult = channel.unary_unary(
                '/meridian.ForecastService/GetForecastResult',
                request_serializer=forecast__pb2.JobID.SerializeToString,
                response_deserializer=forecast__pb2.ForecastResult.FromString,
                _registered_method=True)


class ForecastServiceServicer(object):
    """─── Main Service ────────────────────────────────────────────────

    """

    def SubmitForecastJob(self, request, context):
        """Submit a new forecast job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Check job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForecastResult(self, request, context):
        """Get completed forecast result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForecastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitForecastJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitForecastJob,
                    request_deserializer=forecast__pb2.ForecastRequest.FromString,
                    response_serializer=forecast__pb2.JobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=forecast__pb2.JobID.FromString,
                    response_serializer=forecast__pb2.JobStatusResponse.SerializeToString,
            ),
            'GetForecastResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForecastResult,
                    request_deserializer=forecast__pb2.JobID.FromString,
                    response_serializer=forecast__pb2.ForecastResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meridian.ForecastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meridian.ForecastService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForecastService(object):
    """─── Main Service ────────────────────────────────────────────────

    """

    @staticmethod
    def SubmitForecastJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.ForecastService/SubmitForecastJob',
            forecast__pb2.ForecastRequest.SerializeToString,
            forecast__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.ForecastService/GetJobStatus',
            forecast__pb2.JobID.SerializeToString,
            forecast__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetForecastResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.ForecastService/GetForecastResult',
            forecast__pb2.JobID.SerializeToString,
            forecast__pb2.ForecastResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
