# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'forecast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66orecast.proto\x12\x08meridian\"O\n\x0f\x46orecastRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61taset_ref\x18\x02 \x01(\t\x12\x14\n\x0chorizon_days\x18\x03 \x01(\x05\"\x17\n\x05JobID\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"-\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"Z\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nmodel_used\x18\x03 \x01(\t\x12\x11\n\terror_msg\x18\x04 \x01(\t\"\xa9\x01\n\x0e\x46orecastResult\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nmodel_used\x18\x02 \x01(\t\x12\r\n\x05\x64\x61tes\x18\x03 \x03(\t\x12\x13\n\x0bpredictions\x18\x04 \x03(\x01\x12\x13\n\x0bupper_bound\x18\x05 \x03(\x01\x12\x13\n\x0blower_bound\x18\x06 \x03(\x01\x12%\n\x06scores\x18\x07 \x01(\x0b\x32\x15.meridian.ModelScores\"G\n\x0bModelScores\x12\x13\n\x0bprophet_mae\x18\x01 \x01(\x01\x12\x11\n\tarima_mae\x18\x02 \x01(\x01\x12\x10\n\x08lstm_mae\x18\x03 \x01(\x01\x32\xd6\x01\n\x0f\x46orecastService\x12\x45\n\x11SubmitForecastJob\x12\x19.meridian.ForecastRequest\x1a\x15.meridian.JobResponse\x12<\n\x0cGetJobStatus\x12\x0f.meridian.JobID\x1a\x1b.meridian.JobStatusResponse\x12>\n\x11GetForecastResult\x12\x0f.meridian.JobID\x1a\x18.meridian.ForecastResultB#\n\x12\x63om.meridian.protoB\rForecastProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.meridian.protoB\rForecastProto'
  _globals['_FORECASTREQUEST']._serialized_start=28
  _globals['_FORECASTREQUEST']._serialized_end=107
  _globals['_JOBID']._serialized_start=109
  _globals['_JOBID']._serialized_end=132
  _globals['_JOBRESPONSE']._serialized_start=134
  _globals['_JOBRESPONSE']._serialized_end=179
  _globals['_JOBSTATUSRESPONSE']._serialized_start=181
  _globals['_JOBSTATUSRESPONSE']._serialized_end=271
  _globals['_FORECASTRESULT']._serialized_start=274
  _globals['_FORECASTRESULT']._serialized_end=443
  _globals['_MODELSCORES']._serialized_start=445
  _globals['_MODELSCORES']._serialized_end=516
  _globals['_FORECASTSERVICE']._serialized_start=519
  _globals['_FORECASTSERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
